// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhistleblowingApp.Data;

#nullable disable

namespace WhistleblowingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WhistleblowingApp.Models.MessaggioChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mittente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SegnalazioneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegnalazioneId");

                    b.ToTable("ChatMessaggi");
                });

            modelBuilder.Entity("WhistleblowingApp.Models.Segnalazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltriAConoscenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataIllecito")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("OraIllecito")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PericoloImminente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersoneCoinvolte")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RischioRitorsione")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Segnalazioni");
                });

            modelBuilder.Entity("WhistleblowingApp.Models.MessaggioChat", b =>
                {
                    b.HasOne("WhistleblowingApp.Models.Segnalazione", "Segnalazione")
                        .WithMany("MessaggiChat")
                        .HasForeignKey("SegnalazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segnalazione");
                });

            modelBuilder.Entity("WhistleblowingApp.Models.Segnalazione", b =>
                {
                    b.Navigation("MessaggiChat");
                });
#pragma warning restore 612, 618
        }
    }
}
